language: node_js
os:
  - linux
  - windows
env:
  # fix stuck windows jobs
  # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/13
  - YARN_GPG=no

node_js:
  - "8"
  - "10"
  - "12"
  - "14"
