# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout tagged commit'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          cache: yarn
      - name: 'Install dependencies'
        run: yarn --frozen-lockfile
      - name: 'Publish dotenv-flow@next'
        if: github.event.prerelease == true
        run: yarn publish --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}
      - name: 'Publish dotenv-flow@latest'
        if: github.event.prerelease == false
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}
